name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Miniconda
      run: |
        wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash miniconda.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda init bash
    - name: Install dependencies
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate base
        conda install -y flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate base
        conda install -y pytest
        pytest